### ISSUE TITLE
Using in production

### ISSUE THREAD

**Issue by chintan-mishra** [skunkwerks/sofa#3]
We are releasing an internal tool as an [open source application](https://thenexus.codes) for helping people in their work. CouchDB plays a central role in the infrastructure.

We earlier used ICouch. However, it is not being maintained.

What do you think about using Sofa in production?

**Comment by dch** [comment]
My plan is to replace icouch with sofa in our apps too. We are already using it in production.

I don’t anticipate major changes but the plan is to make it as ecto repo like as possible and it may be that I have to tweak stuff to fit that approach. I would welcome some comments and feedback on how it fits and also what views should look like, from that perspective too.

Ultimately I want to roll it in to Bowie (see hex.pm) once complete, and then, in future, splice it into couchdb itself so you can run it “inside” the database directly with the same api if needed.

I think you should be fine in Production but you may need to use the master commits and ensure you set http timeouts appropriately. The latter is the fiddliest bit to get right!

I may shift it to use gun directly or katipo NIF in future but that won’t change the external api at all. I have not found that Tesla is a great modular interface and it makes testing more awkward than say bypass.

Keep me posted and happy to chat longer over irc.
